### ISSUE TITLE
webkitgtk sends a "load_failed" signal for certain url schems in ubuntu 20.04

### ISSUE THREAD

**Issue by DharshanBJ** [WebKitGTK/webkitgtk.org#13]
Hey folks, this is regarding an issue i'm hitting with webkitgtk on ubuntu, i see that webkitgtk sends a load failed signal for certain type of redirect url navigations, i tried enabling a number of different settings of webkitgtk related to data urls, file urls navigation, but it dosen't seem to help with this issue, any ideas as to why this might be happening?

Some of the url navigations for which the webkitgtk sends a load failed signal:
Error Code 101, Context 'Navigation to URL 'msauth://com.msft.authentication.testapp/<>' failed'
Error Code 102, Context 'Navigation to URL 'https://login.live.com/oauth20<>srf' failed'
Error Code 101, Context 'Navigation to URL 'msauth://com.microsoft.identity.client.sample.local/<>' failed'
Error Code 2, Context 'Navigation to URL 'https://msidlab<>.onmicrosoft.com/SinglePageApp-jQuery-DotNet' failed'
Error Code 4, Context 'Navigation to URL 'http://localhost' failed'

These are the different webkitgtk settings that i enabled for our webview object, but this didn’t help
WebKitSettings* settings = webkit_settings_new();
    webkit_settings_set_allow_top_navigation_to_data_urls(settings,true);
    webkit_settings_set_allow_file_access_from_file_urls(settings, true);
    webkit_settings_set_allow_universal_access_from_file_urls(settings, true);
    webkit_settings_set_enable_spatial_navigation(settings, true);
    webkit_settings_set_enable_back_forward_navigation_gestures(settings, true);
    webkit_settings_set_enable_caret_browsing(settings, true);
    webkit_settings_set_enable_private_browsing(settings,true);
    webkit_settings_set_enable_media_stream(settings, true);
    webkit_web_view_set_settings(_webView.get(),settings);

Please let me know if any additional information is needed, any pointers would be highly appreciated.

**Comment by aperezdc** [comment]
Could you report this at [bugs.webkit.org](https://bugs.webkit.org)?

This GitHub repository is only for the [webkitgtk.org](https://webkitgtk.org) website and its contents.
